pipeline{
    agent any
    tools{
        maven 'M2_HOME'
    }

    stages{
        stage("sonarscan"){
            steps{
                withSonarQubeEnv('SonarQube'){
sh  'mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=ofnarcisse_geo-app'
                }
              
            }

        }
        stage("maven"){
            steps{
            sh 'mvn clean validate compile install test package'
            }
        }
            stage('upload artifact'){
               steps{
                sh 'curl -uadmin:AP7DNrJMUoYbkfoqvYADaS8hmor -T\
                 target/bio*.jar \
                 "http://54.87.132.100:8081/artifactory/geolocation/geo/bio_${BUILD_ID}.jar"'
               } 
            }
        }
    }